language: r
cache: packages
warnings_are_errors: true

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev

branches:
  except:
  - /-expt$/
  notifications:
    email:
      on_success: change
      on_failure: change
